# Generated by Django 5.2.9 on 2025-12-17 22:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("make", models.CharField(max_length=128)),
                ("model", models.CharField(max_length=128)),
                ("year", models.PositiveIntegerField()),
                ("vin", models.CharField(max_length=17, unique=True)),
                ("type", models.CharField(max_length=64)),
                ("base_price_per_day", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("rented", "Rented"),
                            ("service", "In Service"),
                        ],
                        default="available",
                        max_length=16,
                    ),
                ),
                ("mileage", models.PositiveIntegerField(default=0)),
                ("last_service_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["make", "model", "year"],
            },
        ),
    ]
