# Generated by Django 5.0.6 on 2025-09-19 23:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                ("vin", models.CharField(max_length=32, unique=True)),
                ("type", models.CharField(max_length=50)),
                (
                    "base_price_per_day",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("rented", "Rented"),
                            ("service", "In service"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("mileage", models.PositiveIntegerField(default=0)),
                ("last_service_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["make", "model", "year"],
            },
        ),
    ]
