# Generated by Django 5.0.6 on 2025-09-19 23:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("duration", "Duration discount"),
                            ("year", "Year depreciation"),
                            ("seasonal", "Seasonal adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("params", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
