# Generated by Django 5.2.9 on 2025-12-17 22:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("seasonal", "Seasonal"),
                            ("duration_discount", "Duration Discount"),
                            ("year_depreciation", "Year Depreciation"),
                        ],
                        max_length=64,
                    ),
                ),
                ("params", models.JSONField(default=dict)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
